plugins { id 'com.android.application' }

android {
    namespace 'com.luis.participaciones.secundaria'
    compileSdk 35

    signingConfigs {
        personal {
            storeFile file('participaciones-release.jks')
            storePassword 'Participaciones2026'
            keyAlias 'participaciones'
            keyPassword 'Participaciones2026'
        }
    }

    defaultConfig {
        applicationId 'com.luis.participaciones.secundaria'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        debug { signingConfig signingConfigs.personal }
    }
}
